set_property SRC_FILE_INFO {cfile:{C:/Users/mafassi/Desktop/13MHz_UART_25Ko_parity/Vivado project/Microblaze5.srcs/constrs_1/new/si21225.xdc} rfile:../../../Microblaze5.srcs/constrs_1/new/si21225.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports out_N_0]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports out_P_0]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports clk_out1]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports baudrate_out]
