# Contraintes pour la mémoire QSPI externe 50 MHz SPIx1
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
# set_property ram_decomp power [get_cells myram]
# set_property cascade_height 1 [get_cells myram] - 

set_property IOSTANDARD LVCMOS33 [get_ports out_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports out_P_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out1]
set_property PACKAGE_PIN R3 [get_ports out_N_0]
set_property PACKAGE_PIN T3 [get_ports out_P_0]
set_property PACKAGE_PIN T1 [get_ports clk_out1]

set_property IOSTANDARD LVCMOS33 [get_ports baudrate_out]
set_property PACKAGE_PIN U1 [get_ports baudrate_out]

set_property IOSTANDARD LVCMOS33 [get_ports GPIO_IN_tri_i[0]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_IN_tri_i[1]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_IN_tri_i[2]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_IN_tri_i[3]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_IN_tri_i[4]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_IN_tri_i[5]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_IN_tri_i[6]]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_OUT_tri_o[0]]
set_property PACKAGE_PIN V8 [get_ports GPIO_IN_tri_i[0]]
set_property PACKAGE_PIN U8 [get_ports GPIO_IN_tri_i[1]]
set_property PACKAGE_PIN W7 [get_ports GPIO_IN_tri_i[2]]
set_property PACKAGE_PIN U7 [get_ports GPIO_IN_tri_i[3]]
set_property PACKAGE_PIN U3 [get_ports GPIO_IN_tri_i[4]]
set_property PACKAGE_PIN W6 [get_ports GPIO_IN_tri_i[5]]
set_property PACKAGE_PIN U2 [get_ports GPIO_IN_tri_i[6]]
set_property PACKAGE_PIN U5 [get_ports GPIO_OUT_tri_o[0]]
